version: '3.9'

services:
  backend:
    env_file:
      - ./backend/.env.local
    environment:
      - ENV=development
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
    command: npm run dev
    environment:
      - NODE_ENV=development