version: '3.9'

services:
  nginx:
    image: nginx:1.27
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: fastapi_app
    expose:
      - "8000"
    env_file:
      - ./backend/.env.production
    environment:
      - ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - db
    networks:
      - appnet

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_app
    expose:
      - "3000"
    command: npm run start
    env_file:
      - ./frontend/.env.production
    environment:
      - NODE_ENV=production
    networks:
      - appnet
  
  db:
    image: pgvector/pgvector:0.8.0-pg15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init_vector.sql:ro
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  pgdata: